### ISSUE TITLE
Integrate with Sublime Package Control

### ISSUE THREAD

**Issue by nlloyd** [nlloyd/SubliminalCollaborator#15]

**Comment by BrianGilbert** [comment]
Here are the instruction on how to do this to just in case
http://wbond.net/sublime_packages/package_control/package_developers

**Comment by nlloyd** [comment]
Done and waiting for wbond to handle the pull request.  Closing the issue but this plugin won't actually be available until [the pull request](https://github.com/wbond/package_control_channel/pull/839) is handled.
