### ISSUE TITLE
Progress update?

### ISSUE THREAD

**Issue by a-c-m** [nlloyd/SubliminalCollaborator#2]
Hi there,

Stumbled onto this, looks VERY interesting. I was wondering if work is ongoing or if its stopped? Also if there was a non coding way people could help (funds, testing, documentation etc). Or if you know of any other solutions?

I've tried installing it to my /Packages folder (OSX), its picking up the commands ok, but i think i'm missing how to set up the IRC connection and/if there is anything else thats needed to get things moving?

Are you using this in your day to day work?

Cheers,

a_c_m

**Comment by a-c-m** [comment]
Ok, so updated the settings system to use the connection params and got it connecting to IRC.

However looks like the connection to IRC and connection to the partner is all thats working as none of the actions are transmitted. 

Any news on this?

**Comment by nlloyd** [comment]
Hi a_c_m,

This project is still in its infancy and thus hasn't gotten much further then "single awkward connection over IRC to share a single file and only show highlighted sections".  Additionally it is low on my current priority list for projects I am working on, though I do plan on returning to this and taking it beyond the rough hack stage.

At this point I need that most valuable of non-transferable resources: time!

I do not right now use this in my day-to-day work, but that is the intent once it starts becoming more than it is.  I am, however, extremely glad to see that more people than myself are interested :-)

-Nick

**Comment by a-c-m** [comment]
I managed to see it trying to show highlighted sections, but i don't think i ever got that to work.

If you were to make a chip-in / other reverse auction / fund raising thing, i would happily try to make this a priority for you :P as i know quite a few people who would really like to have this functionality. 

How much $ would that take? And when might you be able to squeeze it into your schedule?

**Comment by nlloyd** [comment]
Financial support would be greatly appreciated and I will certainly make this much more of a priority.  This will take some time to move it from the barely-functioning semi-demo that it is now into something real but give me a month to get something more in here.  I will start fleshing out target features soon.

**Comment by jcasimir** [comment]
If it'd get this to a point where I can use it for remote pairing, I could donate at least $1K.

**Comment by a-c-m** [comment]
@jcasimir he has just added a donate button, i'm going to put $25 in the pot and see what i can get other people to add.

**Comment by MarioRicalde** [comment]
I some how got excited over the "feature" section in the readme. Then read this…

**Comment by nlloyd** [comment]
For anyone who is watching this particular thread/issue.  I am "closing" this since I have continued a few weeks ago active development of this tool and, as of just a few minutes ago, merged the alpha branch into master.  In short: progress, and more to come!
