### ISSUE TITLE
reactor is invoked outside of reactor thread, leading to crashes, unreliability

### ISSUE THREAD

**Issue by glyph** [nlloyd/SubliminalCollaborator#23]
For example, at the module level in commands.py, connectAllChat() calls negotiatorInstances[...].connect(), which calls reactor.connectTCP, but the reactor is started in a thread via `ReactorThread`.  This is not allowed by the API, and is probably the cause for this gross (unnecessary, incorrect) change: https://github.com/nlloyd/SubliminalCollaborator/commit/528280f66059bb241867d69a49e45934e2bc4f9f 

To integrate with the sublime main loop, you probably want to use Threaded Select Reactor - http://twistedmatrix.com/trac/browser/trunk/twisted/internet/_threadedselect.py; particularly you want to use .interleave() rather than .run().  It would also be good to have some kind of cooperation mechanism so that if other Sublime plugins want to use Twisted, they could too.

I know that most APIs within Twisted that start with an underscore are not for external usage; for most users, I would advise against using TSR, but a GUI with an unknown / inaccessible event loop like Sublime Text is exactly the (unusual) use-case that it was designed for.

**Comment by nlloyd** [comment]
Thanks for the suggestion!  I completely forgot about that bad hack I put in around the selectreactor.  Experimenting with Threaded Select Reactor right now.  I always feel better when I can clean up a nasty hack I put in for a better solution.
