### ISSUE TITLE
Cannot start a session

### ISSUE THREAD

**Issue by jakepearson** [nlloyd/SubliminalCollaborator#25]
I am trying to get 2 computers within my office to collaborate with one another.  I connected them both to a room on chat.freenode.net.  I start a session on one, and see a popup with a request to start a session on the other.  I press ok, then the connection fails with a timeout (after less than a second).  Here is the output from the console. I get the same message in both directions.  I am using the latest version available on PackageControl.  Here is the output after trying to connect in both directions:

```
[SubliminalCollaborator(INFO): Connecting to chat irc|jake-sublime@chat.freenode.net:6667]
[SubliminalCollaborator|IRC(INFO): Connected to chat.freenode.net]
[SubliminalCollaborator|IRC(INFO): Establishing session with slimer-sublime at 10.32.32.222:55959]
[SubliminalCollaborator|Peer(INFO): Connecting to peer at 10.32.32.222:55959]
[SubliminalCollaborator|Peer(ERROR): Connection failed: <class 'twisted.internet.error.TimeoutError'> - User timeout caused connection failure.]
[SubliminalCollaborator|IRC(WARNING): All connections to all possible host ip addresses failed.]
[SubliminalCollaborator(DEBUG): Cleaning up hosted session with slimer-sublime]
[SubliminalCollaborator|IRC(INFO): Establishing session with slimer-sublime at 10.32.32.222:56100]
[SubliminalCollaborator|Peer(INFO): Connecting to peer at 10.32.32.222:56100]
[SubliminalCollaborator|Peer(ERROR): Connection failed: <class 'twisted.internet.error.TimeoutError'> - User timeout caused connection failure.]
[SubliminalCollaborator|IRC(WARNING): All connections to all possible host ip addresses failed.]
[SubliminalCollaborator(DEBUG): Cleaning up hosted session with slimer-sublime]
[SubliminalCollaborator(DEBUG): select user from client irc|jake-sublime@chat.freenode.net:6667]
[SubliminalCollaborator(DEBUG): Found negotiator for irc|jake-sublime@chat.freenode.net:6667, using it]
[SubliminalCollaborator(DEBUG): Opening collaboration session with user slimer-sublime on client irc|jake-sublime@chat.freenode.net:6667]
[SubliminalCollaborator|Peer(INFO): Listening for peers at :64114]
[SubliminalCollaborator(DEBUG): Cleaning up hosted session with slimer-sublime]
[SubliminalCollaborator|IRC(WARNING): Unable to connect to peer slimer-sublime, all host addresses tried and failed!]
```

Thanks, Jake

**Comment by nlloyd** [comment]
You closed the issue, does that mean it is working now?  The logic in the plugin is pretty barebones around connections (hence the NAT tunneling issue on the project TODO list).  Anything that you found which needs attention?  What solved the problem for you?

**Comment by jakepearson** [comment]
I'm pretty sure it is something NAT related.  I tried it on a laptop on wifi and a desktop on ethernet.  When I switched to 2 desktops the problem went away.  I suspect it is something wrong on my end.  Nothing you need to check into.  Thanks for the tool and for asking.

**Comment by nlloyd** [comment]
No problem.  I very much want this tool to be useful (particularly for myself), so any way I can make it better...  NAT tunneling is top of my list (no ETA yet though...).
