### ISSUE TITLE
Stop carrying patch that changes dccDoChat behavior.

### ISSUE THREAD

**Issue by glyph** [nlloyd/SubliminalCollaborator#26]
The bundled copy of Twisted was changed here - https://github.com/nlloyd/SubliminalCollaborator/commit/22238014eeec2d6b43629bc47e837edde367e3fb - but without any indication that a ticket was filed upstream.  As per #24, this behavior would be problematic if any other Sublime plugins want to use Twisted's IRC / DCC support.

Please file a bug upstream.  Changing dccDoChat's signature in this way is an [incompatible change](http://twistedmatrix.com/trac/wiki/CompatibilityPolicy), so an upstream patch will need to use a different callback.

**Comment by nlloyd** [comment]
Still need to submit the patch but for now this is isolated to a distinct sub-class for better manageability around Twisted upgrades.

**Comment by glyph** [comment]
Woot!  A subclass is definitely not ideal, but it's sure better than carrying a patch.  Thanks!
