### ISSUE TITLE
Stop carrying patch to 'join' behavior

### ISSUE THREAD

**Issue by glyph** [nlloyd/SubliminalCollaborator#27]
In https://github.com/nlloyd/SubliminalCollaborator/commit/c2aa679e20b7b3fb397fa04bd9a63257509b0342 the behavior of twisted.words.protocols.irc was patched, without reference to an upstream ticket.  Please report the issue upstream and remove this modification.

**Comment by nlloyd** [comment]
I am going to remove this behavior.  I don't think it needs to be included in the mainline of twisted.

**Comment by glyph** [comment]
Thanks!

**Comment by nlloyd** [comment]
Removed in refactor.
