### ISSUE TITLE
Stop carrying patch for Twisted ticket 3275.

### ISSUE THREAD

**Issue by glyph** [nlloyd/SubliminalCollaborator#28]
See http://twistedmatrix.com/trac/ticket/3275

It looks like you've already commented there, this is just a reminder that you should eventually merge those changes back upstream ;).

**Comment by nlloyd** [comment]
https://twistedmatrix.com/trac/ticket/3275#comment:14

I will keep track of this and for now in my development work I am going to move the changes to my subclass.

**Comment by glyph** [comment]
Thanks for following up with these changes.

Subclassing is not great, but it's totally a step up from monkeypatching :).
