### ISSUE TITLE
Not able to connect to IRC Server over SSL

### ISSUE THREAD

**Issue by parris** [nlloyd/SubliminalCollaborator#30]
Hi!
So, I am trying to connect subliminal collaborator to our company's internal IRC server. SubliminalCollaborator will either report "connecting to irc|parris@irc.servername.com:6667" or "connection lost to irc|....".

We have some internal docs on how we are supposed to connect to the IRC server. Which involve the following:

```
Server: irc.servername.com
Port: 6667
Server password: ****
SSL: yes
Accept invalid SSL cert: No. The connection is encrypted using a signed certificate from digicert.
```

Here are my settings:

```
{
    "subliminal_collaborator": {
        "irc": [
            {
                "host": "irc.servername.com",
                "port": 6667,
                "username": "parris",
                "password": "****",
                "channel": "channel"
            }
        ],
        "connect_all_on_startup": false
    }
}
```

The sublime console says:

```
[SubliminalCollaborator(INFO): Connecting to chat irc|parris@irc.servername.com:6667]
[SubliminalCollaborator|IRC(INFO): Connected to irc.servername.com]
[SubliminalCollaborator|IRC(ERROR): Connection lost: <class 'twisted.internet.error.ConnectionLost'> - Connection to the other side was lost in a non-clean fashion.]
```

Does pluggin work with IRC channels over SSL?

**Comment by parris** [comment]
I have patch that just works for us right now: https://github.com/parris/SubliminalCollaborator , I need to generalize SSL into an option though then write a test.

**Off Topic Question:** I'm still confused about changing views mid session. Do you need to kill the current session and start a new one in order to share views? Is it possible to share multiple files at once?

**Comment by nlloyd** [comment]
I will take a look at the patch and see what I can do about integrating that, thank you for sharing!

Off Topic Answer: A session is tied to a view and lives for as long as you let it live (or the other person lets it live).  You should be able to have multiple shared views open without issue, with different people or even the same person (not 100% on that list bit, it has been a while since I was in the code).  Create an issue if this is not the case though.

**Comment by hidinginabunker** [comment]
+1 for supporting SSL connections.  Running your own irc server to establish sessions is doable but it's a pretty big workaround.

**Comment by eugenpirogoff** [comment]
+1 for SSL
