### ISSUE TITLE
Feature Request: use XMPP instead of, or in additon to IRC protocol

### ISSUE THREAD

**Issue by soulhakr** [nlloyd/SubliminalCollaborator#32]
XMPP is popular, widely-used protocol for communication/collaboration/etc. However, IRC usage has been diminishing of late. Any chance of implementing XMPP?

**Comment by bastiao** [comment]
True. I strongly believe that it will be a good contribution if we can use Gtalk or something.

**Comment by nlloyd** [comment]
Duplicate of issue #4, I have always planned to include XMPP, I only started with IRC as I felt it would be an easier way to get the basics worked out.
